
- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      -  curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

- name: add GPG key
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: start docker 
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Creates directory
  ansible.builtin.file:
    path: /mywebsite
    state: directory

- name: copy files
  copy: 
    src: "{{ role_path }}/files/mywebsite/"
    dest: /{{ destin_folder }}

- name: docker build image
  ansible.builtin.command:
    chdir: /mywebsite/
    cmd: docker build -t mywebsite .
  
- name: start docker container
  ansible.builtin.command:
    cmd: docker run -d -p 80:80 -p 443:443 mywebsite
